spring.application.name=AssignmentProject
spring.data.mongodb.uri=mongodb+srv://badrinathnooka2085_db_user:XbB3GUpDtxgm9eJH@cluster0.k7n8njt.mongodb.net/starwar?retryWrites=true&w=majority
spring.data.mongodb.database=starwar
server.port=8080
ollama.base-url=http://127.0.0.1:11434
ollama.model=llama3.2
spring.graphql.graphiql.enabled=true
spring.graphql.schema.locations=classpath:schema.graphqls
logging.level.root=INFO
logging.level.notprivacysafe.graphql=DEBUG
logging.level.graphql=DEBUG
logging.level.com.example=DEBUG
